/**
 * Build the single-file version.
 *
 * The modular page needs a web server: browsers refuse ES module imports from
 * a file:// origin, so double-clicking index.html renders a dead page -- the
 * drop zone does nothing and Convert does nothing, with no error a person
 * would see. That is a poor failure for a tool whose whole selling point is
 * that it needs no server.
 *
 *     node web/build.mjs
 *
 * Each module is wrapped in its own function scope and its exports returned,
 * so private names never meet. Flat concatenation was tried first and broke
 * immediately: convert.js and geometry.js both declare UTM_MIN_LAT, which is
 * exactly the collision module scope exists to prevent.
 *
 * The transform is literal rather than a real parser. That is safe here
 * because these are our own modules, written in one style, with no circular
 * imports -- and because the result is parsed and then run against the same
 * cross-checks as the modular version. If either stops being true, use a real
 * bundler rather than trusting this.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));

// Dependency order. A module may only import what precedes it.
const MODULES = [
  "zip.js",
  "xlsx.js",
  "convert.js",
  "unzip.js",
  "archive.js",
  "geometry.js",
  "table.js",
  "workbook.js",
  "kml.js",
  "pipeline.js",
];

const IMPORT = /^import\s*\{([^}]*)\}\s*from\s*["']\.\/([^"']+)["'];?\s*$/gm;

/** Rewrite one module into a body plus the names it exports. */
function transform(source, name) {
  const exported = new Set();

  // import { a, b } from "./x.js"  ->  const { a, b } = __modules["x.js"];
  let body = source.replace(IMPORT, (_match, names, from) => {
    return `const {${names}} = __modules[${JSON.stringify(from)}];`;
  });

  // export { a, b };  -- names are already declared; record and drop.
  body = body.replace(/^export\s*\{([^}]*)\}\s*;?\s*$/gm, (_match, names) => {
    for (const entry of names.split(",")) {
      const clean = entry.trim().split(/\s+as\s+/).pop().trim();
      if (clean) exported.add(clean);
    }
    return "";
  });

  // export function f / const X / class C  -- keep the declaration.
  body = body.replace(
    /^export\s+(function|const|let|class|async function)\s+([A-Za-z_$][\w$]*)/gm,
    (_match, keyword, declared) => {
      exported.add(declared);
      return `${keyword} ${declared}`;
    },
  );

  if (/^\s*(import|export)\s/m.test(body)) {
    const stray = body.match(/^\s*(import|export)\s.*$/m)[0].trim();
    throw new Error(`${name}: unhandled module syntax -> ${stray}`);
  }
  if (!exported.size) throw new Error(`${name}: exported nothing`);

  const names = [...exported].sort();
  return `__modules[${JSON.stringify(name)}] = (function () {
${body.trim()}
return { ${names.join(", ")} };
})();`;
}

const wrapped = MODULES.map((name) =>
  transform(readFileSync(join(here, "src", name), "utf8"), name),
).join("\n\n");

const page = readFileSync(join(here, "index.html"), "utf8");
const open = '<script type="module">';
const start = page.indexOf(open);
const end = page.indexOf("</script>", start);
if (start === -1 || end === -1) throw new Error("could not find the page's module script");

// The page's own imports resolve against the registry the same way.
const pageScript = page
  .slice(start + open.length, end)
  .replace(IMPORT, (_match, names, from) =>
    `const {${names}} = __modules[${JSON.stringify(from.replace(/^src\//, ""))}];`,
  );

const singleFile =
  page.slice(0, start) +
  "<script>\n" +
  "// Built by web/build.mjs from web/src/ -- do not edit this file.\n" +
  "const __modules = {};\n\n" +
  wrapped +
  "\n\n// ---- page ----\n" +
  pageScript +
  "</script>" +
  page.slice(end + "</script>".length);

// An optional destination, so the staleness check can build somewhere
// harmless and compare. Without it that check rebuilt the committed file in
// place, which made it self-healing: a genuine failure disappeared if you
// simply ran the suite twice, and a test run left a tracked file modified.
const target = process.argv[2]
  ? resolve(process.cwd(), process.argv[2])
  : join(here, "kmz-extractor.html");
writeFileSync(target, singleFile);
console.log(
  `wrote ${target} (${(singleFile.length / 1024).toFixed(0)} KB, no dependencies, no server)`,
);
